version: "{build}"
image: Visual Studio 2017

skip_tags: true

build:
  verbosity: detailed

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build_script:
  - gradlew.bat assemble --no-daemon

test_script:
  - gradlew.bat check --no-daemon

cache:
  -  C:\Users\appveyor\.gradle
